default:
  operating_system: "WINDOWS"
  num_cores:      12
  blended:        FALSE
  schema_name:    "transfer"
  drop_schema:    TRUE
  create_schema:  TRUE
  download_data:  FALSE
  create_empty_tables: TRUE

indices:
  DailyMaxTemp:         TRUE
  DailyMinTemp:         TRUE
  DailyMeanTemp:        TRUE     
  DailyPrecipAmount:    TRUE
  DailyMeanSeaLVLPress: TRUE
  DailyCloudCover:      TRUE
  DailyHumid:           TRUE
  DailySnowDepth:       TRUE
  DailySunShineDur:     TRUE
  DailyMeanWindSpeed:   TRUE
  DailyMaxWindGust:     TRUE
  DailyWindDirection:   TRUE

packages: ["data.table","RPostgreSQL", "stringr",
           "reshape2","yaml","markdown","rmarkdown", "gsubfn",
           "SqlRender", "htmltools","foreach", "doParallel", "DBI", "RODBC","odbc"
          ]

database_config:
  type:          "postgresql"
  username:      "postgres"
  password:      "postgres"
  database_name: "meteo_data"
  localhost:     "localhost"
  from_sql:      "postgresql"
  to_sql:        "postgresql"
  port:          5432
  driver:        "PostgreSQL"
