default:
  operating_system: "WINDOWS"
  num_cores:      6
  blended:        FALSE
  schema_name:    "transfer"
  drop_schema:    FALSE
  create_schema:  TRUE
  download_data:  FALSE
  create_empty_tables: TRUE

indices:
  DailyMaxTemp:         FALSE
  DailyMinTemp:         FALSE
  DailyMeanTemp:        FALSE     
  DailyPrecipAmount:    FALSE
  DailyMeanSeaLVLPress: FALSE
  DailyCloudCover:      FALSE
  DailyHumid:           TRUE
  DailySnowDepth:       FALSE
  DailySunShineDur:     FALSE
  DailyMeanWindSpeed:   FALSE
  DailyMaxWindGust:     FALSE
  DailyWindDirection:   FALSE

packages: ["data.table","RPostgreSQL", "stringr",
           "reshape2","yaml","markdown","rmarkdown", "gsubfn",
           "SqlRender", "htmltools","foreach", "doParallel", "DBI", "RODBC","odbc"
          ]

database_config:
  type:          "postgresql"
  username:      "postgres"
  password:      "postgres"
  database_name: "meteo_data"
  localhost:     "localhost"
  from_sql:      "postgresql"
  to_sql:        "postgresql"
  port:          5432
  driver:        "PostgreSQL"
